let computadoras = [
    {
      id: 1,
      nombre: "Combo Básico",
      procesador: "Intel Core i3",
      ram: "8GB",
      almacenamiento: "500GB HDD",
      tarjetaGrafica: "Integrada",
      tarjetaMadre: "ASUS Prime A320M-K",
      fuentePoder: "450W",
      disipador: "Disipador estándar",
      precio: 400,
    },
    {
      id: 2,
      nombre: "Combo Intermedio",
      procesador: "AMD Ryzen 3",
      ram: "16GB",
      almacenamiento: "256GB SSD",
      tarjetaGrafica: "NVIDIA GTX 1050",
      tarjetaMadre: "MSI B450M PRO-VDH",
      fuentePoder: "550W",
      disipador: "Cooler Master Hyper 212",
      precio: 600,
    },
    {
      id: 3,
      nombre: "Combo Avanzado",
      procesador: "Intel Core i7",
      ram: "32GB",
      almacenamiento: "1TB SSD",
      tarjetaGrafica: "NVIDIA GTX 1660",
      tarjetaMadre: "Gigabyte Z490 Gaming X",
      fuentePoder: "650W",
      disipador: "Noctua NH-U12S",
      precio: 1000,
    },
    {
      id: 4,
      nombre: "Combo Personalizado 4",
      procesador: "AMD Ryzen 5",
      ram: "40GB",
      almacenamiento: "512GB SSD",
      tarjetaGrafica: "AMD Radeon RX 580",
      tarjetaMadre: "ASUS TUF Gaming B550-PLUS",
      fuentePoder: "450W",
      disipador: "Disipador estándar",
      precio: 775,
    },
    {
      id: 5,
      nombre: "Combo Personalizado 5",
      procesador: "Intel Core i5",
      ram: "8GB",
      almacenamiento: "2TB HDD",
      tarjetaGrafica: "NVIDIA GTX 1660",
      tarjetaMadre: "MSI MPG Z490 GAMING EDGE",
      fuentePoder: "550W",
      disipador: "Cooler Master Hyper 212",
      precio: 850,
    },
    {
      id: 6,
      nombre: "Combo Personalizado 6",
      procesador: "Intel Core i9",
      ram: "16GB",
      almacenamiento: "1TB HDD",
      tarjetaGrafica: "NVIDIA RTX 3060",
      tarjetaMadre: "Gigabyte AORUS B450 Elite",
      fuentePoder: "650W",
      disipador: "Noctua NH-D15",
      precio: 925,
    },
    {
      id: 7,
      nombre: "Combo Personalizado 7",
      procesador: "AMD Ryzen 7",
      ram: "24GB",
      almacenamiento: "512GB SSD",
      tarjetaGrafica: "AMD Radeon RX 6700 XT",
      tarjetaMadre: "ASRock B560 Pro4",
      fuentePoder: "750W",
      disipador: "Disipador estándar",
      precio: 1000,
    },
    {
      id: 8,
      nombre: "Combo Personalizado 8",
      procesador: "AMD Ryzen 5",
      ram: "32GB",
      almacenamiento: "2TB HDD",
      tarjetaGrafica: "NVIDIA RTX 4090",
      tarjetaMadre: "ASUS TUF Gaming B550-PLUS",
      fuentePoder: "450W",
      disipador: "Cooler Master Hyper 212",
      precio: 1075,
    },
    {
      id: 9,
      nombre: "Combo Personalizado 9",
      procesador: "Intel Core i5",
      ram: "40GB",
      almacenamiento: "1TB HDD",
      tarjetaGrafica: "AMD Radeon RX 580",
      tarjetaMadre: "MSI MPG Z490 GAMING EDGE",
      fuentePoder: "550W",
      disipador: "Noctua NH-U12S",
      precio: 1150,
    },
    {
      id: 10,
      nombre: "Combo Personalizado 10",
      procesador: "Intel Core i9",
      ram: "8GB",
      almacenamiento: "512GB SSD",
      tarjetaGrafica: "NVIDIA GTX 1660",
      tarjetaMadre: "Gigabyte AORUS B450 Elite",
      fuentePoder: "650W",
      disipador: "Noctua NH-D15",
      precio: 1225,
    },
    {
      id: 11,
      nombre: "Combo Personalizado 11",
      procesador: "AMD Ryzen 7",
      ram: "16GB",
      almacenamiento: "2TB HDD",
      tarjetaGrafica: "NVIDIA RTX 3060",
      tarjetaMadre: "ASRock B560 Pro4",
      fuentePoder: "750W",
      disipador: "Disipador estándar",
      precio: 1300,
    },
    {
      id: 12,
      nombre: "Combo Personalizado 12",
      procesador: "AMD Ryzen 5",
      ram: "24GB",
      almacenamiento: "1TB HDD",
      tarjetaGrafica: "AMD Radeon RX 570",
      tarjetaMadre: "ASUS TUF Gaming B450M-PLUS",
      fuentePoder: "500W",
      disipador: "Cooler Master Hyper 212",
      precio: 950,
    },
    {
      id: 13,
      nombre: "Combo Personalizado 13",
      procesador: "Intel Core i5",
      ram: "32GB",
      almacenamiento: "512GB SSD",
      tarjetaGrafica: "NVIDIA GTX 1650",
      tarjetaMadre: "MSI B560M PRO-VDH",
      fuentePoder: "650W",
      disipador: "Noctua NH-U12S",
      precio: 1025,
    },
    {
      id: 14,
      nombre: "Combo Personalizado 14",
      procesador: "Intel Core i9",
      ram: "40GB",
      almacenamiento: "2TB HDD",
      tarjetaGrafica: "NVIDIA GTX 1660 Super",
      tarjetaMadre: "Gigabyte Z490 AORUS Ultra",
      fuentePoder: "750W",
      disipador: "Noctua NH-D15",
      precio: 1350,
    },
    {
      id: 15,
      nombre: "Combo Personalizado 15",
      procesador: "AMD Ryzen 7",
      ram: "8GB",
      almacenamiento: "1TB HDD",
      tarjetaGrafica: "AMD Radeon RX 5500 XT",
      tarjetaMadre: "ASRock B450 Steel Legend",
      fuentePoder: "550W",
      disipador: "Disipador estándar",
      precio: 890,
    },
    {
      id: 16,
      nombre: "Combo Personalizado 16",
      procesador: "AMD Ryzen 5",
      ram: "16GB",
      almacenamiento: "512GB SSD",
      tarjetaGrafica: "NVIDIA GTX 1050 Ti",
      tarjetaMadre: "ASUS Prime B450M-A",
      fuentePoder: "500W",
      disipador: "Cooler Master Hyper 212",
      precio: 975,
    },
    {
      id: 17,
      nombre: "Combo Personalizado 17",
      procesador: "Intel Core i5",
      ram: "24GB",
      almacenamiento: "2TB HDD",
      tarjetaGrafica: "NVIDIA GTX 1650",
      tarjetaMadre: "MSI MAG B550M Mortar",
      fuentePoder: "600W",
      disipador: "Noctua NH-U12S",
      precio: 1050,
    },
    {
      id: 18,
      nombre: "Combo Personalizado 18",
      procesador: "Intel Core i9",
      ram: "32GB",
      almacenamiento: "1TB HDD",
      tarjetaGrafica: "AMD Radeon RX 5700",
      tarjetaMadre: "Gigabyte B450 AORUS M",
      fuentePoder: "700W",
      disipador: "Noctua NH-D15",
      precio: 1200,
    },
    {
      id: 19,
      nombre: "Combo Personalizado 19",
      procesador: "AMD Ryzen 7",
      ram: "40GB",
      almacenamiento: "512GB SSD",
      tarjetaGrafica: "NVIDIA GTX 1660",
      tarjetaMadre: "ASRock B560 Pro4",
      fuentePoder: "650W",
      disipador: "Disipador estándar",
      precio: 1100,
    },
    {
      id: 20,
      nombre: "Combo Personalizado 20",
      procesador: "AMD Ryzen 5",
      ram: "8GB",
      almacenamiento: "2TB HDD",
      tarjetaGrafica: "NVIDIA GTX 1050",
      tarjetaMadre: "ASUS Prime A320M-K",
      fuentePoder: "450W",
      disipador: "Cooler Master Hyper 212",
      precio: 875,
    },
    {
      id: 21,
      nombre: "Combo Personalizado 21",
      procesador: "Intel Core i5",
      ram: "16GB",
      almacenamiento: "1TB HDD",
      tarjetaGrafica: "NVIDIA GTX 1650",
      tarjetaMadre: "MSI B460M PRO-VDH",
      fuentePoder: "550W",
      disipador: "Cooler Master Hyper 212",
      precio: 970,
    },
    {
      id: 22,
      nombre: "Combo Personalizado 22",
      procesador: "Intel Core i9",
      ram: "24GB",
      almacenamiento: "512GB SSD",
      tarjetaGrafica: "AMD Radeon RX 580",
      tarjetaMadre: "ASUS TUF Gaming Z490-PLUS",
      fuentePoder: "750W",
      disipador: "Noctua NH-D15",
      precio: 1250,
    },
    {
      id: 23,
      nombre: "Combo Personalizado 23",
      procesador: "AMD Ryzen 7",
      ram: "32GB",
      almacenamiento: "2TB HDD",
      tarjetaGrafica: "NVIDIA GTX 1660 Super",
      tarjetaMadre: "Gigabyte B550M DS3H",
      fuentePoder: "600W",
      disipador: "Noctua NH-U12S",
      precio: 1150,
    },
    {
      id: 24,
      nombre: "Combo Personalizado 24",
      procesador: "AMD Ryzen 5",
      ram: "40GB",
      almacenamiento: "1TB HDD",
      tarjetaGrafica: "AMD Radeon RX 5700 XT",
      tarjetaMadre: "ASRock B450M Steel Legend",
      fuentePoder: "650W",
      disipador: "Cooler Master Hyper 212",
      precio: 1020,
    },
    {
      id: 25,
      nombre: "Combo Personalizado 25",
      procesador: "Intel Core i5",
      ram: "8GB",
      almacenamiento: "512GB SSD",
      tarjetaGrafica: "NVIDIA GTX 1050 Ti",
      tarjetaMadre: "MSI MAG B550 TOMAHAWK",
      fuentePoder: "500W",
      disipador: "Disipador estándar",
      precio: 800,
    },
    {
      id: 26,
      nombre: "Combo Personalizado 26",
      procesador: "Intel Core i9",
      ram: "16GB",
      almacenamiento: "2TB HDD",
      tarjetaGrafica: "AMD Radeon RX 6700 XT",
      tarjetaMadre: "ASUS Prime Z490-A",
      fuentePoder: "750W",
      disipador: "Noctua NH-D15",
      precio: 1350,
    },
    {
      id: 27,
      nombre: "Combo Personalizado 27",
      procesador: "AMD Ryzen 7",
      ram: "24GB",
      almacenamiento: "1TB HDD",
      tarjetaGrafica: "NVIDIA GTX 1660",
      tarjetaMadre: "Gigabyte B450 AORUS Elite",
      fuentePoder: "600W",
      disipador: "Cooler Master Hyper 212",
      precio: 1050,
    },
    {
      id: 28,
      nombre: "Combo Personalizado 28",
      procesador: "AMD Ryzen 5",
      ram: "32GB",
      almacenamiento: "512GB SSD",
      tarjetaGrafica: "NVIDIA GTX 1050 Ti",
      tarjetaMadre: "ASUS TUF B450-PLUS Gaming",
      fuentePoder: "500W",
      disipador: "Disipador estándar",
      precio: 940,
    },
    {
      id: 29,
      nombre: "Combo Personalizado 29",
      procesador: "Intel Core i5",
      ram: "40GB",
      almacenamiento: "2TB HDD",
      tarjetaGrafica: "AMD Radeon RX 5500 XT",
      tarjetaMadre: "MSI B550M PRO-VDH WiFi",
      fuentePoder: "650W",
      disipador: "Cooler Master Hyper 212",
      precio: 1100,
    },
    {
      id: 30,
      nombre: "Combo Personalizado 30",
      procesador: "Intel Core i9",
      ram: "8GB",
      almacenamiento: "1TB HDD",
      tarjetaGrafica: "NVIDIA GTX 1050",
      tarjetaMadre: "ASRock Z490 Phantom Gaming",
      fuentePoder: "550W",
      disipador: "Noctua NH-U12S",
      precio: 980,
    },
    {
      id: 31,
      nombre: "Combo Personalizado 31",
      procesador: "AMD Ryzen 7",
      ram: "16GB",
      almacenamiento: "512GB SSD",
      tarjetaGrafica: "NVIDIA GTX 1650 Super",
      tarjetaMadre: "MSI B450 TOMAHAWK MAX",
      fuentePoder: "600W",
      disipador: "Cooler Master Hyper 212",
      precio: 1100,
    },
    {
      id: 32,
      nombre: "Combo Personalizado 32",
      procesador: "AMD Ryzen 5",
      ram: "24GB",
      almacenamiento: "2TB HDD",
      tarjetaGrafica: "AMD Radeon RX 5600 XT",
      tarjetaMadre: "ASUS ROG Strix B450-F",
      fuentePoder: "650W",
      disipador: "Noctua NH-U12S",
      precio: 1050,
    },
    {
      id: 33,
      nombre: "Combo Personalizado 33",
      procesador: "Intel Core i5",
      ram: "32GB",
      almacenamiento: "1TB HDD",
      tarjetaGrafica: "NVIDIA GTX 1660 Ti",
      tarjetaMadre: "Gigabyte B460M DS3H",
      fuentePoder: "600W",
      disipador: "Cooler Master Hyper 212",
      precio: 1200,
    },
    {
      id: 34,
      nombre: "Combo Personalizado 34",
      procesador: "Intel Core i9",
      ram: "40GB",
      almacenamiento: "512GB SSD",
      tarjetaGrafica: "AMD Radeon RX 5700 XT",
      tarjetaMadre: "ASRock B550 Phantom Gaming",
      fuentePoder: "750W",
      disipador: "Noctua NH-D15",
      precio: 1350,
    },
    {
      id: 35,
      nombre: "Combo Personalizado 35",
      procesador: "AMD Ryzen 7",
      ram: "8GB",
      almacenamiento: "2TB HDD",
      tarjetaGrafica: "NVIDIA GTX 1050",
      tarjetaMadre: "MSI B450-A PRO",
      fuentePoder: "500W",
      disipador: "Disipador estándar",
      precio: 900,
    },
    {
      id: 36,
      nombre: "Combo Personalizado 36",
      procesador: "AMD Ryzen 5",
      ram: "16GB",
      almacenamiento: "1TB HDD",
      tarjetaGrafica: "AMD Radeon RX 580",
      tarjetaMadre: "Gigabyte A520M S2H",
      fuentePoder: "550W",
      disipador: "Cooler Master Hyper 212",
      precio: 1000,
    },
    {
      id: 37,
      nombre: "Combo Personalizado 37",
      procesador: "Intel Core i5",
      ram: "24GB",
      almacenamiento: "512GB SSD",
      tarjetaGrafica: "NVIDIA GTX 1660",
      tarjetaMadre: "ASRock B560 Pro4",
      fuentePoder: "650W",
      disipador: "Cooler Master Hyper 212",
      precio: 1150,
    },
    {
      id: 38,
      nombre: "Combo Personalizado 38",
      procesador: "Intel Core i9",
      ram: "32GB",
      almacenamiento: "2TB HDD",
      tarjetaGrafica: "AMD Radeon RX 6700",
      tarjetaMadre: "ASUS TUF Gaming B560M-PLUS",
      fuentePoder: "750W",
      disipador: "Noctua NH-D15",
      precio: 1400,
    },
    {
      id: 39,
      nombre: "Combo Personalizado 39",
      procesador: "AMD Ryzen 7",
      ram: "40GB",
      almacenamiento: "1TB HDD",
      tarjetaGrafica: "NVIDIA GTX 1660 Super",
      tarjetaMadre: "MSI MAG B550M Mortar",
      fuentePoder: "600W",
      disipador: "Cooler Master Hyper 212",
      precio: 1300,
    },
    {
      id: 40,
      nombre: "Combo Personalizado 40",
      procesador: "AMD Ryzen 5",
      ram: "8GB",
      almacenamiento: "512GB SSD",
      tarjetaGrafica: "AMD Radeon RX 550",
      tarjetaMadre: "ASUS Prime A320M-K",
      fuentePoder: "500W",
      disipador: "Disipador estándar",
      precio: 850,
    },
  ];
  